name: Build Mobile

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
    - working-directory: ./mobile
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - uses: actions/upload-artifact@v4
      with:
        name: ios-artifact
        path: build/ios/
